<#
.SYNOPSIS
  Menghasilkan THIRD_PARTY_LICENSES.md: lisensi semua dependensi Rust dan font yang ikut
  dalam binary KOHA.

.DESCRIPTION
  Daftar paket diambil dari `cargo tree` (dependensi normal untuk target Windows), berkas
  lisensi tiap paket dibaca dari registry Cargo lokal, dan teks yang identik dikelompokkan
  supaya berkas hasil tidak berlipat ganda. Font diambil dari crates/koha-gui/assets/fonts.

  Paket yang tidak membawa berkas lisensi di paket terbitannya TIDAK disembunyikan: mereka
  dicantumkan di bagian tersendiri dan dilaporkan sebagai peringatan.

  Berkas ini membantu memenuhi kewajiban menyertakan pemberitahuan lisensi saat binary
  dibagikan. Ini bukan nasihat hukum.

.PARAMETER Check
  Tidak menulis apa pun; membandingkan hasil dengan berkas yang ada dan keluar dengan kode 1
  bila berbeda (berguna untuk CI).

.PARAMETER Target
  Target yang dipakai untuk menentukan dependensi. Bawaan: x86_64-pc-windows-msvc.

.EXAMPLE
  .\tools\gen-third-party.ps1

.EXAMPLE
  .\tools\gen-third-party.ps1 -Check
#>
[CmdletBinding()]
param(
  [switch]$Check,
  [string]$Target = 'x86_64-pc-windows-msvc'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
Set-Location $root
$outFile = Join-Path $root 'THIRD_PARTY_LICENSES.md'

function ConvertTo-Lf([string]$text) { ($text -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd() }

# Pastikan sumber semua paket ada di registry lokal.
cargo fetch --locked --target $Target | Out-Null
if ($LASTEXITCODE -ne 0) { throw 'cargo fetch gagal' }

$cargoHome = if ($env:CARGO_HOME) { $env:CARGO_HOME } else { Join-Path $env:USERPROFILE '.cargo' }
$registrySrc = Join-Path $cargoHome 'registry\src'

# ---------------------------------------------------------------- paket Rust
$treeLines = cargo tree -p koha-app --target $Target -e normal --prefix none --locked --format '{p}|{l}|{r}'
if ($LASTEXITCODE -ne 0) { throw 'cargo tree gagal' }

$packages = @{}
foreach ($line in $treeLines) {
  if ($line -notmatch '^(?<name>[A-Za-z0-9_\-]+) v(?<ver>[0-9][^ |]*)(?<rest>[^|]*)\|(?<lic>[^|]*)\|(?<repo>.*)$') { continue }
  if ($Matches.rest -match '\([A-Za-z]:\\|\(/') { continue }   # crate lokal milik proyek ini
  $key = "$($Matches.name) $($Matches.ver)"
  if (-not $packages.ContainsKey($key)) {
    $packages[$key] = [pscustomobject]@{
      Name = $Matches.name; Version = $Matches.ver
      License = $Matches.lic.Trim(); Repo = $Matches.repo.Trim()
    }
  }
}
$sorted = @($packages.Values | Sort-Object Name, Version)
if ($sorted.Count -eq 0) { throw 'tidak ada paket yang terbaca dari cargo tree' }

$texts = @{}          # sha256 -> @{ Text; Users = list }
$noFiles = New-Object System.Collections.Generic.List[object]
foreach ($pkg in $sorted) {
  $dir = Get-ChildItem -LiteralPath $registrySrc -Directory |
    ForEach-Object { Join-Path $_.FullName "$($pkg.Name)-$($pkg.Version)" } |
    Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
  if (-not $dir) { throw "sumber $($pkg.Name) $($pkg.Version) tidak ditemukan di $registrySrc" }

  $files = @(Get-ChildItem -LiteralPath $dir -File | Where-Object { $_.Name -match '^(?i)(LICEN[CS]E|COPYING|UNLICENSE|NOTICE)' } | Sort-Object Name)
  if ($files.Count -eq 0) { $noFiles.Add($pkg); continue }
  foreach ($file in $files) {
    $text = ConvertTo-Lf ([IO.File]::ReadAllText($file.FullName))
    if (-not $text) { continue }
    $sha = [BitConverter]::ToString([Security.Cryptography.SHA256]::Create().ComputeHash([Text.Encoding]::UTF8.GetBytes($text))) -replace '-', ''
    if (-not $texts.ContainsKey($sha)) { $texts[$sha] = [pscustomobject]@{ Text = $text; Users = New-Object System.Collections.Generic.List[string]; First = "$($pkg.Name) $($pkg.Version)" } }
    $label = "$($pkg.Name) $($pkg.Version)"
    if (-not $texts[$sha].Users.Contains($label)) { $texts[$sha].Users.Add($label) }
  }
}

# --------------------------------------------------------------------- font
$fontDirs = @(Get-ChildItem -LiteralPath (Join-Path $root 'crates\koha-gui\assets\fonts') -Directory | Sort-Object Name)

# -------------------------------------------------------------------- tulis
$sb = New-Object System.Text.StringBuilder
function Add-Line([string]$s = '') { [void]$sb.Append($s).Append("`n") }

Add-Line '# Third-party licenses'
Add-Line
Add-Line 'KOHA includes the third-party components listed below. Their licenses apply to those'
Add-Line 'components; they say nothing about KOHA itself.'
Add-Line
Add-Line 'This file is generated by `tools/gen-third-party.ps1` from the dependency graph for'
Add-Line "``$Target`` and the fonts under ``crates/koha-gui/assets/fonts``. Do not edit it by hand;"
Add-Line 're-run the script instead (`-Check` verifies that it is up to date).'
Add-Line
Add-Line '## Fonts'
Add-Line
Add-Line 'The following fonts are embedded in the binary. They are licensed under the SIL Open'
Add-Line 'Font License, Version 1.1 (the full text is reproduced for each font below).'
Add-Line
foreach ($dir in $fontDirs) {
  $ofl = Join-Path $dir.FullName 'OFL.txt'
  $ttf = Get-ChildItem -LiteralPath $dir.FullName -Filter '*.ttf' | Select-Object -First 1
  $text = ConvertTo-Lf ([IO.File]::ReadAllText($ofl))
  $copyright = ($text -split "`n")[0]
  Add-Line "### $($dir.Name) ($($ttf.Name))"
  Add-Line
  Add-Line $copyright
  Add-Line
  Add-Line '```text'
  Add-Line $text
  Add-Line '```'
  Add-Line
}

Add-Line '## Rust dependencies'
Add-Line
Add-Line "$($sorted.Count) packages are linked into the Windows build."
Add-Line
Add-Line '| Package | Version | License | Source |'
Add-Line '|---|---|---|---|'
foreach ($pkg in $sorted) {
  $lic = if ($pkg.License) { $pkg.License } else { '(not declared)' }
  $repo = if ($pkg.Repo) { $pkg.Repo } else { "https://crates.io/crates/$($pkg.Name)/$($pkg.Version)" }
  Add-Line "| $($pkg.Name) | $($pkg.Version) | $lic | $repo |"
}
Add-Line

$mpl = @($sorted | Where-Object { $_.License -match 'MPL' })
if ($mpl.Count -gt 0) {
  Add-Line '### Source code for MPL-licensed packages'
  Add-Line
  Add-Line 'The following packages are licensed under the Mozilla Public License 2.0. KOHA uses them'
  Add-Line 'unmodified. Their source code is available from the locations below:'
  Add-Line
  foreach ($pkg in $mpl) { Add-Line "- $($pkg.Name) $($pkg.Version): https://crates.io/crates/$($pkg.Name)/$($pkg.Version) ($($pkg.Repo))" }
  Add-Line
}

Add-Line '### License texts'
Add-Line
Add-Line 'Identical license texts are shown once, followed by the packages that use them.'
Add-Line
$n = 0
foreach ($entry in ($texts.Values | Sort-Object First)) {
  $n++
  Add-Line "#### License text $n"
  Add-Line
  Add-Line ('Used by: ' + (($entry.Users | Sort-Object) -join ', '))
  Add-Line
  Add-Line '```text'
  Add-Line $entry.Text
  Add-Line '```'
  Add-Line
}

if ($noFiles.Count -gt 0) {
  Add-Line '### Packages without a license file in their published package'
  Add-Line
  Add-Line 'These packages declare a license in their metadata but do not ship the license text'
  Add-Line 'in the published crate. The declared license expression is listed; see the source'
  Add-Line 'repository for the text.'
  Add-Line
  foreach ($pkg in $noFiles) {
    $repo = if ($pkg.Repo) { $pkg.Repo } else { "https://crates.io/crates/$($pkg.Name)/$($pkg.Version)" }
    Add-Line "- $($pkg.Name) $($pkg.Version): $($pkg.License) ($repo)"
  }
  Add-Line
  Write-Warning ("{0} paket tanpa berkas lisensi: {1}" -f $noFiles.Count, (($noFiles | ForEach-Object { "$($_.Name) $($_.Version)" }) -join ', '))
}

$content = $sb.ToString().TrimEnd() + "`n"

if ($Check) {
  $existing = if (Test-Path -LiteralPath $outFile) { ConvertTo-Lf ([IO.File]::ReadAllText($outFile)) } else { '' }
  if ($existing -ne (ConvertTo-Lf $content)) {
    Write-Error 'THIRD_PARTY_LICENSES.md tidak mutakhir. Jalankan .\tools\gen-third-party.ps1 lalu commit hasilnya.'
    exit 1
  }
  Write-Host 'THIRD_PARTY_LICENSES.md sudah mutakhir.'
  exit 0
}

[IO.File]::WriteAllText($outFile, $content, (New-Object System.Text.UTF8Encoding $false))
Write-Host ("Ditulis: {0} ({1:N0} byte, {2} paket, {3} teks lisensi unik, {4} tanpa berkas lisensi)" -f $outFile, $content.Length, $sorted.Count, $texts.Count, $noFiles.Count)
